import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FileText, LinkSimple, ShieldCheck } from "@phosphor-icons/react";
export function EvidencePanel({ evidence, relation }) {
    return (_jsxs("div", { className: "evidenceTabPanel", children: [_jsxs("div", { className: "detailCard", children: [_jsxs("div", { children: [_jsx("p", { className: "sectionEyebrow compact", children: "Evidence" }), _jsx("strong", { children: relation ? "Relation-scoped source cards" : "Evidence placeholder" })] }), _jsx("p", { children: relation ? relation.summary : "Select a relation to inspect citations and confidence labels." }), relation ? (_jsxs("div", { className: "metaGrid compact", children: [_jsx("span", { children: "Relationship" }), _jsx("strong", { children: relation.relationshipSemanticLabel }), _jsx("span", { children: "Subtype" }), _jsx("strong", { children: relation.relationshipSubtypeLabel ?? "Not specified" }), _jsx("span", { children: "Source method" }), _jsx("strong", { children: relation.sourceMethodLabel ?? "Not specified" }), _jsx("span", { children: "Evidence precision" }), _jsx("strong", { children: relation.evidenceDateResolutionLabel ?? "Not specified" }), _jsx("span", { children: "Validity" }), _jsx("strong", { children: relation.validityLabel })] })) : null] }), _jsx("div", { className: "evidenceList", children: evidence.map((item) => (_jsxs("article", { className: "evidenceCard", children: [_jsxs("div", { className: "relationMeta", children: [_jsxs("span", { className: "miniBadge", children: [_jsx(FileText, { size: 12 }), " ", item.sourceTypeLabel] }), _jsxs("span", { className: `confidenceBadge ${item.confidence}`, children: [_jsx(ShieldCheck, { size: 12 }), " ", formatConfidence(item.confidence)] })] }), _jsx("strong", { children: item.title }), _jsx("p", { children: item.citation }), _jsxs("div", { className: "evidenceFooter", children: [_jsx("span", { children: item.publisher }), _jsx("span", { children: item.publishedAt })] }), _jsxs("a", { href: item.url, target: "_blank", rel: "noreferrer", children: [_jsx(LinkSimple, { size: 14 }), "Open source"] })] }, item.id))) }), _jsxs("div", { className: "detailCard provenanceCard", children: [_jsx("p", { className: "sectionEyebrow compact", children: "Evidence provenance" }), _jsxs("div", { className: "provenanceGrid", children: [_jsx("span", { children: "Document" }), _jsx("strong", { children: evidence[0]?.sourceTypeLabel ?? "10-K / Report" }), _jsx("span", { children: "Filed date" }), _jsx("strong", { children: evidence[0]?.publishedAt ?? "Pending source binding" }), _jsx("span", { children: "Issuer" }), _jsx("strong", { children: evidence[0]?.publisher ?? "Company / publisher" }), _jsx("span", { children: "Access" }), _jsx("strong", { children: evidence[0]?.url ? "External source ready" : "Connector pending" })] })] })] }));
}
function formatConfidence(value) {
    if (value === "strong_evidence")
        return "Strong evidence";
    return value.charAt(0).toUpperCase() + value.slice(1);
}
