import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CornersOut, Minus, Plus } from "@phosphor-icons/react";
import { getRelationshipTypeLabel } from "../utils/relationSemantics.js";
export function GraphCanvas(props) {
    const { activeNodeId, activeRelationId, focusNode, graph, onNodeSelect, onRelationSelect, onZoomChange, zoom } = props;
    return (_jsxs("section", { className: "graphWorkspace", children: [_jsxs("div", { className: "workspaceHeader", children: [_jsxs("div", { children: [_jsx("h3", { children: "Global Supply Chain Map" }), _jsx("p", { children: "Relationship type and tier depth are encoded directly on the dark graph workspace." }), _jsx("p", { children: "Nodes distinguish group anchors, brand/legal naming, and facility operators instead of flattening all aliases into one surface." })] }), _jsxs("div", { className: "workspaceTopline", children: [_jsxs("div", { className: "inlineLegend", children: [_jsx("span", { children: "Relationship Type" }), graph.relationTypeOptions.map((option) => (_jsxs("strong", { children: [option.label, _jsx("small", { children: option.count })] }, option.value)))] }), _jsxs("div", { className: "inlineLegend", children: [_jsx("span", { children: "Tier Depth" }), _jsx("strong", { children: "1" }), _jsx("strong", { children: "2" }), _jsx("strong", { children: "3" }), _jsx("strong", { children: "4+" })] })] })] }), _jsxs("div", { className: "graphViewport", children: [_jsx("div", { className: "graphViewportOverlay" }), _jsx("div", { className: "graphDust" }), _jsx("svg", { viewBox: "0 0 100 100", role: "img", "aria-label": `${graph.focusCompany.name} supply chain graph`, children: _jsxs("g", { transform: `scale(${zoom}) translate(${(1 - zoom) * 50} ${(1 - zoom) * 50})`, children: [graph.relations.map((relation) => {
                                    const source = graph.nodes.find((node) => node.id === relation.sourceId);
                                    const target = graph.nodes.find((node) => node.id === relation.targetId);
                                    if (!source || !target)
                                        return null;
                                    const isActive = relation.id === activeRelationId;
                                    return (_jsxs("g", { children: [_jsx("path", { className: isActive ? "graphEdge active" : "graphEdge", d: curvePath(source, target), onClick: () => onRelationSelect(relation) }), _jsx("text", { className: "graphEdgeLabel", x: (source.x + target.x) / 2, y: (source.y + target.y) / 2 - 2, children: getRelationshipTypeLabel(relation.relationshipType) })] }, relation.id));
                                }), graph.nodes.map((node) => {
                                    const radius = node.kind === "company" ? 5.8 + node.importanceScore * 2.2 : 1.8 + node.importanceScore * 2.8;
                                    return (_jsxs("g", { className: node.id === activeNodeId ? "graphNode active" : "graphNode", transform: `translate(${node.x} ${node.y})`, onClick: () => onNodeSelect(node), children: [_jsx("circle", { r: radius }), _jsx("text", { y: radius + 4.2, children: node.label })] }, node.id));
                                })] }) }), _jsxs("div", { className: "miniMapPlaceholder", children: [_jsx("div", { className: "miniMapHeader", children: "Mini-map" }), _jsx("div", { className: "miniMapFrame" })] }), _jsxs("div", { className: "zoomCluster", children: [_jsx("button", { className: "iconButton", type: "button", onClick: () => onZoomChange(Math.max(0.8, zoom - 0.1)), children: _jsx(Minus, { size: 16 }) }), _jsx("button", { className: "iconButton", type: "button", onClick: () => onZoomChange(Math.min(1.5, zoom + 0.1)), children: _jsx(Plus, { size: 16 }) }), _jsx("button", { className: "iconButton", type: "button", children: _jsx(CornersOut, { size: 16 }) })] }), _jsxs("div", { className: "marketLegend", children: [_jsx("span", { children: "Market importance by market cap (USD)" }), _jsxs("div", { className: "marketLegendDots", children: [_jsx("i", {}), _jsx("i", {}), _jsx("i", {}), _jsx("i", {}), _jsx("i", {})] })] }), _jsxs("div", { className: "focusPill", children: [_jsx("strong", { children: focusNode.displayName }), _jsx("span", { children: focusNode.secondaryLabel ?? focusNode.region }), _jsx("small", { children: focusNode.hierarchySummary })] })] })] }));
}
function curvePath(source, target) {
    const controlX = (source.x + target.x) / 2;
    const controlY = Math.min(source.y, target.y) - Math.abs(source.x - target.x) * 0.12;
    return `M ${source.x} ${source.y} Q ${controlX} ${controlY} ${target.x} ${target.y}`;
}
