import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { EvidencePanel } from "./EvidencePanel";
export function MobileEvidenceSheet(props) {
    const { activeRelation, activeTab, company, depth, evidence, evidenceError, evidenceLoading, evidenceSummary, onRetryEvidence, onTabChange } = props;
    return (_jsx("section", { className: "mobileEvidenceShell", "aria-label": "\u79FB\u52A8\u7AEF\u8BC1\u636E\u62BD\u5C49\u9AA8\u67B6", children: _jsxs("div", { className: "mobilePhoneFrame", children: [_jsxs("div", { className: "mobilePhoneBar", children: [_jsx("strong", { children: "Mag7 \u4F9B\u5E94\u94FE\u60C5\u62A5\u56FE\u8C31" }), _jsx("span", { children: "9:41" })] }), _jsxs("div", { className: "mobileExplorerPreview", children: [_jsxs("div", { className: "mobileQuickChips", children: [_jsxs("span", { children: [depth, "\u7EA7\u7A7F\u900F"] }), _jsx("span", { children: "\u5168\u5C4F\u63A2\u7D22" })] }), _jsxs("div", { className: "mobileMiniGraph", children: [_jsx("span", { children: company.displayName }), _jsx("small", { children: "\u56FE\u8C31\u4F18\u5148\uFF0C\u8BC1\u636E\u4E00\u89E6\u8FBE" })] })] }), _jsxs("div", { className: "mobileBottomSheet", children: [_jsx("div", { className: "mobileSheetHandle" }), _jsxs("div", { className: "mobileSheetHeader", children: [_jsx("strong", { children: "\u6765\u6E90\u8BC1\u636E" }), _jsx("span", { children: company.displayName })] }), _jsxs("div", { className: "mobileTabs", role: "tablist", "aria-label": "\u79FB\u52A8\u7AEF\u8BE6\u60C5\u6807\u7B7E", children: [_jsx("button", { "aria-selected": activeTab === "overview", className: activeTab === "overview" ? "mobileTab active" : "mobileTab", onClick: () => onTabChange("overview"), role: "tab", type: "button", children: "\u6982\u89C8" }), _jsx("button", { "aria-selected": activeTab === "evidence", className: activeTab === "evidence" ? "mobileTab active" : "mobileTab", onClick: () => onTabChange("evidence"), role: "tab", type: "button", children: "\u8BC1\u636E" }), _jsx("button", { "aria-selected": activeTab === "financials", className: activeTab === "financials" ? "mobileTab active" : "mobileTab", onClick: () => onTabChange("financials"), role: "tab", type: "button", children: "\u8D22\u52A1" })] }), _jsxs("div", { className: "mobileEvidenceKpis", children: [_jsx(Metric, { label: "\u5DF2\u786E\u8BA4", value: evidenceSummary.confirmed }), _jsx(Metric, { label: "\u5F3A\u8BC1\u636E", value: evidenceSummary.strongEvidence }), _jsx(Metric, { label: "\u63A8\u65AD", value: evidenceSummary.inferred })] }), _jsx("div", { className: "mobileEvidenceBody", children: activeTab === "evidence" ? (_jsx(EvidencePanel, { evidence: evidence.slice(0, 2), error: evidenceError, loading: evidenceLoading, onRetry: onRetryEvidence, relation: activeRelation })) : (_jsxs("article", { className: "mobileSummaryCard", children: [_jsx("strong", { children: activeTab === "overview" ? "图谱概览" : "财务摘要" }), _jsx("p", { children: activeTab === "overview"
                                            ? "桌面侧栏在移动端收敛为半开底部抽屉，保留证据与审计信息入口。"
                                            : "财务标签预留市值、关系暴露度与依赖集中度的移动端展示位。" })] })) })] })] }) }));
}
function Metric(props) {
    return (_jsxs("div", { className: "mobileMetric", children: [_jsx("span", { children: props.label }), _jsx("strong", { children: props.value })] }));
}
