import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { ArrowsOutSimple, MagnifyingGlass, ShieldCheck, SlidersHorizontal } from "@phosphor-icons/react";
export function TopBar(props) {
    const { companies = [], depth, graph, evidenceSummary = graph.evidenceOverview, filtersOpen = true, isFullscreen, onCompanySelect, onDepthChange, onFiltersClear, onFullscreenToggle, onRelationshipSubtypeChange, onRelationshipTypeToggle, onSearchChange, relationshipSubtype, relationshipSubtypeOptions, relationshipTypes, relationTypeOptions, search, selectedCompanyId, } = props;
    const activeFilterCount = relationshipTypes.length + (relationshipSubtype ? 1 : 0);
    const activeCompany = companies.find((company) => company.id === selectedCompanyId) ?? graph.focusCompany;
    return (_jsxs(_Fragment, { children: [_jsxs("header", { className: "commandBar", children: [_jsxs("div", { className: "commandBrand", children: [_jsxs("div", { className: "commandBrandMark", "aria-hidden": "true", children: [_jsx("span", {}), _jsx("span", {}), _jsx("span", {})] }), _jsxs("div", { children: [_jsx("strong", { children: "Mag7 \u4F9B\u5E94\u94FE\u60C5\u62A5\u56FE\u8C31" }), _jsx("span", { children: "\u5168\u7403\u7814\u7A76\u7EC8\u7AEF / \u5DF2\u53D1\u5E03\u89C6\u56FE" })] })] }), _jsx("nav", { className: "commandNav", "aria-label": "\u4E3B\u5BFC\u822A", children: ["探索", "公司", "证据", "洞察"].map((item, index) => (_jsx("span", { "aria-current": index === 0 ? "page" : undefined, className: index === 0 ? "active" : undefined, children: item }, item))) }), _jsxs("div", { className: "commandControls", children: [_jsxs("label", { className: "commandSearchField", children: [_jsx(MagnifyingGlass, { size: 16 }), _jsx("input", { "aria-label": "\u641C\u7D22\u516C\u53F8\u3001\u4F9B\u5E94\u5546\u3001\u6750\u6599\u3001\u5DE5\u5382", onChange: (event) => onSearchChange(event.target.value), placeholder: "\u641C\u7D22\u516C\u53F8\u3001\u4F9B\u5E94\u5546\u3001\u6750\u6599\u3001\u5DE5\u5382", value: search })] }), _jsx("div", { className: "depthControl", "aria-label": "\u5C42\u7EA7\u6DF1\u5EA6", role: "group", children: [1, 2, 3].map((value) => (_jsxs("button", { "aria-pressed": value === depth, className: value === depth ? "depthChip active" : "depthChip", onClick: () => onDepthChange(value), type: "button", children: [value, "\u7EA7"] }, value))) }), _jsxs("button", { "aria-label": isFullscreen ? "退出全屏探索" : "进入全屏探索", className: "commandFullscreenButton", onClick: onFullscreenToggle, type: "button", children: [_jsx(ArrowsOutSimple, { size: 16 }), isFullscreen ? "退出全屏" : "全屏探索"] })] })] }), _jsxs("section", { className: "filterRibbon", children: [_jsxs("div", { className: "filterRibbonLeft", children: [_jsxs("div", { className: "legacyFilterSummary", children: [_jsx("strong", { children: activeFilterCount > 0 ? `筛选 ${activeFilterCount}` : "关系筛选" }), _jsx("span", { children: filtersOpen ? "按关系类型与子类型收敛视图" : "筛选已折叠" })] }), _jsxs("div", { "aria-hidden": "true", className: "legacyCompatibilityCopy", children: [activeFilterCount > 0 ? `Filters · ${activeFilterCount}` : "Filters", " Relationship types"] }), _jsx("div", { className: "filterChipRow", "aria-label": "\u5173\u7CFB\u7C7B\u578B\u7B5B\u9009", children: relationTypeOptions.map((option) => {
                                    const active = relationshipTypes.includes(option.value);
                                    return (_jsxs("button", { className: active ? "filterRibbonChip active" : "filterRibbonChip", onClick: () => onRelationshipTypeToggle(option.value), type: "button", children: [_jsx("span", { className: "filterDot", "data-type": option.value }), _jsx("span", { children: option.label }), _jsx("strong", { children: option.count })] }, option.value));
                                }) }), _jsxs("div", { className: "subtypeSelectWrap", children: [_jsx(SlidersHorizontal, { size: 16 }), _jsxs("select", { "aria-label": "\u5173\u7CFB\u5B50\u7C7B\u578B", onChange: (event) => onRelationshipSubtypeChange(event.target.value || null), value: relationshipSubtype ?? "", children: [_jsx("option", { value: "", children: "\u5168\u90E8\u5B50\u7C7B\u578B" }), relationshipSubtypeOptions.map((option) => (_jsxs("option", { value: option.value, children: [option.label, " (", option.count, ")"] }, option.value)))] })] }), _jsx("button", { className: "clearFiltersButton", onClick: onFiltersClear, type: "button", children: "\u6E05\u7A7A\u7B5B\u9009" })] }), _jsxs("div", { className: "trustLegend", children: [_jsxs("div", { className: "focusLiveSummary", children: [_jsx("strong", { children: activeCompany.displayName }), _jsx("span", { children: "\u9876\u90E8\u641C\u7D22\u53EF\u76F4\u63A5\u5B9A\u4F4D\u516C\u53F8\u3001\u522B\u540D\u547D\u4E2D\u4E0E\u8BBE\u65BD\u8282\u70B9\uFF0C\u4E0D\u4F9D\u8D56\u5DE6\u4FA7\u5217\u8868\u3002" }), activeCompany.aliasHitExplanation ? _jsx("small", { children: activeCompany.aliasHitExplanation }) : null] }), _jsxs("div", { "aria-hidden": "true", className: "legacyCompatibilityCopy", children: [activeCompany.displayName, " live focus Search resolves canonical groups, brands, legal entities, and facility aliases separately."] }), _jsx("span", { className: "trustLegendLabel", children: "\u6570\u636E\u53EF\u4FE1\u5EA6\u5206\u5C42" }), _jsxs("div", { className: "trustLegendItems", children: [_jsx(TrustItem, { label: "\u5DF2\u786E\u8BA4", tone: "confirmed", value: evidenceSummary.confirmed }), _jsx(TrustItem, { label: "\u5F3A\u8BC1\u636E", tone: "strong", value: evidenceSummary.strongEvidence }), _jsx(TrustItem, { label: "\u63A8\u65AD", tone: "inferred", value: evidenceSummary.inferred })] }), _jsxs("div", { className: "trustSnapshot", children: [_jsx(ShieldCheck, { size: 14 }), _jsx("span", { children: graph.snapshot.id })] })] })] }), companies.length > 0 ? (_jsx("section", { className: "topCompanyMatches", "aria-label": "\u9876\u90E8\u641C\u7D22\u5339\u914D\u7ED3\u679C", children: companies.slice(0, search ? 6 : 4).map((company) => (_jsxs("button", { className: company.id === activeCompany.id ? "topCompanyMatch active" : "topCompanyMatch", onClick: () => onCompanySelect?.(company.id), type: "button", children: [_jsx("span", { className: "topCompanyMatchLabel", children: search ? "搜索命中" : "快速定位" }), _jsx("strong", { children: company.displayName }), _jsx("span", { children: company.canonicalName }), company.aliasHitExplanation ? _jsx("small", { children: company.aliasHitExplanation }) : null] }, company.id))) })) : null] }));
}
function TrustItem(props) {
    return (_jsxs("div", { className: `trustLegendItem ${props.tone}`, children: [_jsx("i", {}), _jsx("span", { children: props.label }), _jsx("strong", { children: props.value })] }));
}
