import { readFile } from 'node:fs/promises';
import { buildApp } from './src/app.ts';
import { loadNormalizedImportPackage, prepareNormalizedImport } from './src/lib/normalized-package.ts';
import type { CacheClient } from './src/lib/redis.ts';
import type { GraphRepository, Neo4jHealth } from './src/lib/neo4j.ts';
import type { CompanyDetailDTO, CompanyListQuery, CompanyOverviewDTO, CompanySearchMatchDTO, EvidenceDTO, GraphNodeDTO, GraphPathQuery, GraphStatsDTO, GraphStatsQuery, RelationDTO, SnapshotDTO, SubgraphDTO, SubgraphQuery, SearchCompaniesQuery, SuggestCompaniesQuery } from '@mag7/contracts';

const FULL_PACKAGE_DIR = '/workspace/agents/evidence-collector/output/mag7-full-package';
const cache = new Map();
const cacheClient = { enabled: true, async get(k) { return cache.get(k) ?? null; }, async set(k, v) { cache.set(k, v); }, async del(k) { cache.delete(k); }, async health() { return { status: 'up', enabled: true, detail: 'test cache', required: true }; }, async close() {} } satisfies CacheClient;
function matchesSnapshot(snapshotId: string, snapshotQuery: string) { return snapshotQuery === 'published' ? true : snapshotId === snapshotQuery; }
function compareSnapshotRecency(left: Pick<SnapshotDTO,'publishedAt'|'id'> | null, right: Pick<SnapshotDTO,'publishedAt'|'id'> | null) { if (!left && !right) return 0; if (!left) return 1; if (!right) return -1; return (right.publishedAt ?? '').localeCompare(left.publishedAt ?? '') || right.id.localeCompare(left.id); }
function pickLatestSnapshot(snapshots: SnapshotDTO[]) { return [...snapshots].sort(compareSnapshotRecency)[0] ?? null; }
function normalizeSearchValue(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, ''); }
function buildSearchMatch(company: CompanyDetailDTO, query: string): CompanySearchMatchDTO | undefined { const q=normalizeSearchValue(query); for (const c of [{field:'ticker',value:company.ticker},{field:'displayName',value:company.displayName},{field:'canonicalName',value:company.canonicalName},{field:'name',value:company.name}] as const) { if (c.value && normalizeSearchValue(c.value).includes(q)) return { field: c.field, value: c.value, explanation: '' }; } for (const alias of [...(company.entityProfile?.aliases ?? []), ...(company.entityProfile?.legalEntities ?? []), ...(company.entityProfile?.brands ?? [])]) { if (normalizeSearchValue(alias.normalizedName || alias.name).includes(q)) return { field: 'alias', value: alias.name, aliasType: alias.aliasType, explanation: '' }; } for (const alias of company.aliases) { if (normalizeSearchValue(alias).includes(q)) return { field: 'alias', value: alias, explanation: '' }; } }
function sortCompaniesForSearch(left: CompanyDetailDTO, right: CompanyDetailDTO, query: string) { const priority=['ticker','displayName','canonicalName','name','alias']; return priority.indexOf(buildSearchMatch(left, query)?.field ?? 'alias') - priority.indexOf(buildSearchMatch(right, query)?.field ?? 'alias'); }
function pickLatestRelationSnapshotId(relations: Array<Pick<RelationDTO,'snapshotId'|'lastVerifiedAt'>>) { return [...relations].sort((left,right)=>(right.lastVerifiedAt ?? '').localeCompare(left.lastVerifiedAt ?? '') || right.snapshotId.localeCompare(left.snapshotId))[0]?.snapshotId ?? null; }
function buildCompanyDetails(prepared:any) { const byId=new Map<string,CompanyDetailDTO>(); const relationByCompany=new Map<string,{snapshotId:string;lastVerifiedAt:string|null}>(); for (const edge of prepared.relationEdges) { const relation=prepared.relations.find((item:any)=>item.id===edge.relationId); if (!relation) continue; const current=relationByCompany.get(edge.targetCompanyId); const next={snapshotId:edge.snapshotId,lastVerifiedAt:relation.lastVerifiedAt}; if (!current || compareSnapshotRecency({id:next.snapshotId,publishedAt:next.lastVerifiedAt},{id:current.snapshotId,publishedAt:current.lastVerifiedAt}) < 0) relationByCompany.set(edge.targetCompanyId,next); } for (const company of prepared.companies) { const active=relationByCompany.get(company.id); byId.set(company.id,{...company,primaryRegion:company.country,activeSnapshotId:active?.snapshotId ?? null,summary:company.description,lastUpdatedAt:active?.lastVerifiedAt ?? null}); } return byId; }
function buildSubgraph(companyById: Map<string, CompanyDetailDTO>, prepared:any, relations: RelationDTO[]): SubgraphDTO { const nodeMap=new Map<string,GraphNodeDTO>(); for (const relation of relations) { const source=companyById.get(relation.sourceId); const target=companyById.get(relation.targetId); if (source) nodeMap.set(source.id,{id:source.id,entityType:'Company',label:source.displayName ?? source.name,company:source,country:source.country,marketCapUsd:source.marketCapUsd,importanceScore:source.importanceScore}); if (target) nodeMap.set(target.id,{id:target.id,entityType:'Company',label:target.displayName ?? target.name,company:target,country:target.country,marketCapUsd:target.marketCapUsd,importanceScore:target.importanceScore}); } const snapshot=pickLatestSnapshot(relations.map((relation)=>prepared.snapshots.find((s:any)=>s.id===relation.snapshotId) ?? null).filter(Boolean) as SnapshotDTO[]); return { snapshot: snapshot ?? { id: pickLatestRelationSnapshotId(relations) ?? 'snapshot:published', version: (pickLatestRelationSnapshotId(relations) ?? 'snapshot:published').replace('snapshot:','').replace(/-/g,'.'), status: 'published', publishedAt: null, scope: [], notes: null }, nodes: [...nodeMap.values()], relations }; }
class Repo implements GraphRepository { source='neo4j' as const; private readonly companyById: Map<string,CompanyDetailDTO>; private readonly evidenceByRelationId=new Map<string,EvidenceDTO[]>(); private readonly relationById=new Map<string,RelationDTO>(); constructor(private readonly prepared:any){ this.companyById=buildCompanyDetails(prepared); for (const relation of prepared.relations){ this.relationById.set(relation.id,{...relation, sourceId: prepared.relationEdges.find((e:any)=>e.relationId===relation.id)?.sourceCompanyId ?? '', targetId: prepared.relationEdges.find((e:any)=>e.relationId===relation.id)?.targetCompanyId ?? '', status: relation.status }); } for (const binding of prepared.evidenceBindings){ const evNode=prepared.evidence.find((e:any)=>e.id===binding.evidenceId); if (!evNode) continue; const ev: EvidenceDTO = { id: evNode.id, sourceType: evNode.sourceType, skuGranularity: evNode.skuGranularity, skuGranularityDetail: null, title: evNode.title, publisher: evNode.publisher, url: evNode.url, publishedAt: evNode.publishedAt, publishedAtResolution: evNode.publishedAtResolution, coverageStart: evNode.coverageStart, coverageEnd: evNode.coverageEnd, coverageStartResolution: evNode.coverageStartResolution, coverageEndResolution: evNode.coverageEndResolution, retrievedAt: evNode.retrievedAt, excerpt: evNode.excerpt, pageRef: evNode.pageRef, language: evNode.language, hash: evNode.hash, sourceDomain: evNode.sourceDomain, citationText: evNode.citationText, reliabilityTier: evNode.reliabilityTier, licenseNote: evNode.licenseNote, parserVersion: evNode.parserVersion }; const cur=this.evidenceByRelationId.get(binding.relationId) ?? []; cur.push(ev); this.evidenceByRelationId.set(binding.relationId,cur); } }
 async listCompanies(query: CompanyListQuery){ return [...this.companyById.values()].filter((c)=>query.isMag7===undefined?true:c.isMag7===query.isMag7).map((c)=>({id:c.id,ticker:c.ticker,name:c.name,canonicalName:c.canonicalName,displayName:c.displayName,isMag7:c.isMag7,marketCapUsd:c.marketCapUsd,entityProfile:c.entityProfile,primaryRegion:c.primaryRegion,activeSnapshotId:c.activeSnapshotId})); }
 async searchCompanies(query: SearchCompaniesQuery){ return [...this.companyById.values()].filter((c)=>Boolean(buildSearchMatch(c,query.q))).sort((a,b)=>sortCompaniesForSearch(a,b,query.q)).slice(0,query.limit).map((c)=>({id:c.id,ticker:c.ticker,name:c.name,isMag7:c.isMag7,marketCapUsd:c.marketCapUsd,primaryRegion:c.primaryRegion,activeSnapshotId:c.activeSnapshotId,canonicalName:c.canonicalName,displayName:c.displayName,entityProfile:c.entityProfile,match:buildSearchMatch(c,query.q)})); }
 async suggestCompanies(query: SuggestCompaniesQuery){ return [...this.companyById.values()].filter((c)=>Boolean(buildSearchMatch(c,query.q))).sort((a,b)=>sortCompaniesForSearch(a,b,query.q)).slice(0,query.limit).map((c)=>({id:c.id,label:c.ticker?`${c.displayName ?? c.name} (${c.ticker})`:(c.displayName ?? c.name),secondaryLabel:c.canonicalName && c.canonicalName !== c.displayName ? c.canonicalName : undefined,ticker:c.ticker,isMag7:c.isMag7,canonicalName:c.canonicalName,displayName:c.displayName,entityProfile:c.entityProfile,match:buildSearchMatch(c,query.q)})); }
 async getCompany(companyId: string){ return this.companyById.get(companyId) ?? null; }
 async getCompanyOverview(companyId: string): Promise<CompanyOverviewDTO | null>{ const company=this.companyById.get(companyId); if (!company) return null; const related=[...this.relationById.values()].filter((r)=>r.sourceId===companyId || r.targetId===companyId); return { companyId, companyName: company.name, activeSnapshotId: company.activeSnapshotId, totalRelations: related.length, tier1SupplierCount: related.filter((r)=>r.tier===1).length, supplierCount: new Set(related.map((r)=>r.sourceId)).size, highRiskRelationCount: related.filter((r)=>r.confidence !== 'confirmed').length, evidenceCount: related.reduce((s,r)=>s+r.evidenceCount,0), evidenceCoverage: related.length===0?0:related.filter((r)=>r.evidenceCount>0).length/related.length, lastUpdatedAt: company.lastUpdatedAt ?? null, source: this.source }; }
 async getSubgraph(query: SubgraphQuery): Promise<SubgraphDTO>{ const root=this.companyById.get(query.companyId) ?? null; const relations=[...this.relationById.values()].filter((r)=>r.depthFromMag7<=query.depth).filter((r)=>matchesSnapshot(r.snapshotId,query.snapshot)).filter((r)=>r.sourceId===query.companyId || r.targetId===query.companyId).map((r)=>({...r,evidence: query.includeEvidence ? this.evidenceByRelationId.get(r.id) ?? [] : undefined})); if (!relations.length) return { snapshot: { id: root?.activeSnapshotId ?? 'snapshot:published', version: (root?.activeSnapshotId ?? 'snapshot:published').replace('snapshot:','').replace(/-/g,'.'), status: 'published', publishedAt: null, scope: root?[root.id]:[], notes: 'No matching relations for this snapshot filter.' }, nodes: root?[{id:root.id,entityType:'Company',label:root.displayName ?? root.name,company:root,country:root.country,marketCapUsd:root.marketCapUsd,importanceScore:root.importanceScore}]:[], relations: [] }; return buildSubgraph(this.companyById,this.prepared,relations); }
 async getPath(query: GraphPathQuery): Promise<SubgraphDTO>{ const relations=[...this.relationById.values()].filter((r)=>r.depthFromMag7<=query.maxDepth).filter((r)=>matchesSnapshot(r.snapshotId,query.snapshot)).filter((r)=>(r.sourceId===query.sourceCompanyId && r.targetId===query.targetCompanyId) || (r.sourceId===query.targetCompanyId && r.targetId===query.sourceCompanyId)).map((r)=>({...r,evidence: query.includeEvidence ? this.evidenceByRelationId.get(r.id) ?? [] : undefined})); return relations.length?buildSubgraph(this.companyById,this.prepared,relations):{ snapshot: { id:'snapshot:published',version:'published',status:'published',publishedAt:null,scope:[],notes:'No path found.' }, nodes:[], relations:[] }; }
 async getGraphStats(query: GraphStatsQuery): Promise<GraphStatsDTO>{ const scoped=[...this.relationById.values()].filter((r)=>matchesSnapshot(r.snapshotId,query.snapshot) && (!query.companyId || r.sourceId===query.companyId || r.targetId===query.companyId)); const companyIds=new Set<string>(),mag7Ids=new Set<string>(),relationshipTypeBreakdown:Record<string,number>={},confidenceBreakdown:Record<string,number>={},evidenceIds=new Set<string>(); for (const r of scoped){ companyIds.add(r.sourceId); companyIds.add(r.targetId); if (this.companyById.get(r.sourceId)?.isMag7) mag7Ids.add(r.sourceId); if (this.companyById.get(r.targetId)?.isMag7) mag7Ids.add(r.targetId); relationshipTypeBreakdown[r.relationshipType]=(relationshipTypeBreakdown[r.relationshipType]??0)+1; confidenceBreakdown[r.confidence]=(confidenceBreakdown[r.confidence]??0)+1; for (const id of r.evidenceIds) evidenceIds.add(id); } const snapshot=pickLatestSnapshot(scoped.map((r)=>this.prepared.snapshots.find((s:any)=>s.id===r.snapshotId) ?? null).filter(Boolean) as SnapshotDTO[]); return { snapshot, companyCount: companyIds.size, relationCount: scoped.length, evidenceCount: evidenceIds.size, mag7CompanyCount: mag7Ids.size, relationshipTypeBreakdown, confidenceBreakdown, source: this.source }; }
 async getRelationEvidence(relationId: string){ return this.evidenceByRelationId.get(relationId) ?? []; }
 async importNormalizedPackage(payload:any){ return { companyCount: payload.companies.length, relationCount: payload.relations.length, evidenceCount: payload.evidence.length, snapshotCount: payload.snapshots.length }; }
}
const companyMap = { Apple: 'company:AAPL', Alphabet: 'company:GOOGL', Meta: 'company:META', Tesla: 'company:TSLA' };
const newRelationIds = { Apple: ['rel:apple:ups:logistics:launch-air-hub-delivery-sorting','rel:apple:accenture:professional_service:enterprise-transformation-operations-consulting','rel:apple:deloitte:professional_service:enterprise-inventory-backoffice-consulting','rel:apple:sap:professional_service:enterprise-software-business-process'], Alphabet: ['rel:alphabet:voltus:professional_service:distributed-capacity-orchestration-data-centers','rel:alphabet:tennessee-valley-authority:professional_service:data-center-demand-response-utility-agreement','rel:alphabet:entergy-arkansas:professional_service:new-data-center-demand-response-contract','rel:alphabet:minnesota-power:professional_service:new-data-center-demand-response-contract','rel:alphabet:baseload-capital:professional_service:geothermal-power-local-data-centers','rel:alphabet:padget-electronics:manufacturing:pixel-contract-manufacturing-india','rel:alphabet:shenzhen-futaihong:manufacturing:pixel-pro-series-contract-manufacturing','rel:alphabet:f1-info-solutions:professional_service:pixel-after-sales-repair-service-india','rel:alphabet:redington:logistics:pixel-case-import-distribution-india'], Meta: ['rel:meta:amd:component_supply:ai-infrastructure-instinct-epyc-rack-scale-systems','rel:meta:nvidia-spectrum-x-ethernet:component_supply:ai-ethernet-switching-platform','rel:meta:broadcom:component_supply:mtia-custom-ai-accelerators-networking','rel:meta:arista-networks:component_supply:ai-cluster-switch','rel:meta:essilorluxottica:manufacturing:ray-ban-oakley-meta-ai-glasses','rel:meta:constellation-energy:professional_service:nuclear-power-support-operations','rel:meta:vistra:professional_service:grid-power-prometheus-supercluster','rel:meta:sage-geosystems:professional_service:geothermal-power-project'], Tesla: ['rel:tesla:panasonic:manufacturing:battery-cell-production-equipment-finance-lease'] };
const [pkg, manifestRaw] = await Promise.all([loadNormalizedImportPackage(`${FULL_PACKAGE_DIR}/relations.jsonl`, `${FULL_PACKAGE_DIR}/evidence.jsonl`), readFile(`${FULL_PACKAGE_DIR}/mag7-full-package-manifest.json`, 'utf8')]);
const manifest = JSON.parse(manifestRaw);
const prepared = prepareNormalizedImport(pkg);
const app = await buildApp({ cacheClient, graphRepository: new Repo(prepared), neo4jHealth: async (): Promise<Neo4jHealth> => ({ status:'up', detail:'full-package sample repository', required:true }), runtimeMode:'live' });
const out:any = { manifestSummary: { package_snapshot_id: manifest.package_snapshot_id, authoritative_snapshot: manifest.authoritative_snapshot, baseline_snapshot_id: manifest.coverage_summary?.baseline_snapshot_id, formal_net_new_by_company: manifest.coverage_summary?.formal_net_new_by_company, candidate_only: manifest.coverage_summary?.candidate_only }, preparedSummary: { relationCount: prepared.relations.length, evidenceCount: prepared.evidence.length, snapshots: prepared.snapshots.map((s:any)=>s.id) }, companies: {} };
for (const [name,id] of Object.entries(companyMap)) { const [detailRes,overviewRes,subgraphRes,statsRes] = await Promise.all([app.inject({method:'GET',url:`/api/v1/companies/${encodeURIComponent(id)}`}), app.inject({method:'GET',url:`/api/v1/companies/${encodeURIComponent(id)}/overview`}), app.inject({method:'GET',url:`/api/v1/graph/subgraph?companyId=${encodeURIComponent(id)}&depth=3&snapshot=published&includeEvidence=true`}), app.inject({method:'GET',url:`/api/v1/graph/stats?snapshot=published&companyId=${encodeURIComponent(id)}`})]); const detail=detailRes.json(), overview=overviewRes.json(), subgraph=subgraphRes.json(), stats=statsRes.json(); const targetIds=newRelationIds[name as keyof typeof newRelationIds]; const present=targetIds.filter((rid)=>subgraph.relations.some((r:any)=>r.id===rid)); const evidenceStates = []; for (const rid of targetIds) { const evRes=await app.inject({method:'GET',url:`/api/v1/relations/${encodeURIComponent(rid)}/evidence`}); const ev=evRes.json(); evidenceStates.push({ relationId: rid, status: evRes.statusCode, evidenceCount: Array.isArray(ev) ? ev.length : null, firstEvidence: Array.isArray(ev) && ev[0] ? { id: ev[0].id, sourceType: ev[0].sourceType, sourceDomain: ev[0].sourceDomain, publishedAt: ev[0].publishedAt, publishedAtResolution: ev[0].publishedAtResolution, skuGranularity: ev[0].skuGranularity } : null }); } out.companies[name] = { detailStatus: detailRes.statusCode, overviewStatus: overviewRes.statusCode, subgraphStatus: subgraphRes.statusCode, statsStatus: statsRes.statusCode, activeSnapshotId: detail.activeSnapshotId, overview: { totalRelations: overview.totalRelations, evidenceCount: overview.evidenceCount, source: overview.source }, subgraph: { snapshot: subgraph.snapshot, relationCount: subgraph.relations.length, relationshipTypes: [...new Set(subgraph.relations.map((r:any)=>r.relationshipType))].sort(), confidences: [...new Set(subgraph.relations.map((r:any)=>r.confidence))].sort() }, stats: { snapshot: stats.snapshot, relationCount: stats.relationCount, evidenceCount: stats.evidenceCount, confidenceBreakdown: stats.confidenceBreakdown, source: stats.source }, expectedFormalNetNew: targetIds.length, presentFormalNetNewRelationIds: present, missingFormalNetNewRelationIds: targetIds.filter((rid)=>!present.includes(rid)), evidenceStates }; }
await app.close();
console.log(JSON.stringify(out, null, 2));
