import { z } from "zod";
export const backendSourceSchema = z.enum(["neo4j", "mock"]);
export const confidenceSchema = z.enum(["confirmed", "strong_evidence", "inferred"]);
export const relationStatusSchema = z.enum(["draft", "approved", "deprecated", "disputed"]);
export const sourceTypeSchema = z.enum([
    "10k",
    "earnings_call",
    "supplier_report",
    "media",
    "industry_report",
    "press_release",
]);
export const relationshipTypeSchema = z.enum([
    "component_supply",
    "raw_material_supply",
    "manufacturing",
    "cloud_service",
    "logistics",
    "professional_service",
    "equipment_supply",
    "software_dependency",
    "channel_partner",
]);
export const snapshotStatusSchema = z.enum(["draft", "review", "published", "archived"]);
export const entityTypeSchema = z.enum([
    "Company",
    "Facility",
    "Product",
    "Technology",
    "Material",
    "SupplyRelation",
    "Evidence",
    "Snapshot",
]);
export const companySchema = z.object({
    id: z.string(),
    ticker: z.string().optional(),
    name: z.string(),
    entityType: z.literal("Company"),
    companyType: z.enum([
        "public_company",
        "supplier",
        "manufacturer",
        "logistics",
        "service_provider",
        "raw_material",
    ]),
    country: z.string(),
    isMag7: z.boolean(),
    marketCapUsd: z.number().nullable(),
    description: z.string().nullable().optional(),
    aliases: z.array(z.string()).default([]),
    active: z.boolean().default(true),
    importanceScore: z.number().min(0).max(1).optional(),
});
export const companyListItemSchema = z.object({
    id: z.string(),
    ticker: z.string().optional(),
    name: z.string(),
    isMag7: z.boolean(),
    marketCapUsd: z.number().nullable(),
    primaryRegion: z.string(),
    activeSnapshotId: z.string().nullable(),
});
export const companyListQuerySchema = z.object({
    q: z.string().optional(),
    isMag7: z.coerce.boolean().optional(),
    page: z.coerce.number().int().min(1).default(1),
    pageSize: z.coerce.number().int().min(1).max(100).default(20),
});
export const companyListResponseSchema = z.object({
    items: z.array(companyListItemSchema),
    page: z.number().int().min(1),
    pageSize: z.number().int().min(1).max(100),
    total: z.number().int().min(0),
    source: backendSourceSchema,
});
export const evidenceSchema = z.object({
    id: z.string(),
    sourceType: sourceTypeSchema,
    title: z.string(),
    publisher: z.string(),
    url: z.string().url(),
    publishedAt: z.string(),
    retrievedAt: z.string(),
    excerpt: z.string(),
    pageRef: z.string().nullable().optional(),
    language: z.string().default("en"),
    hash: z.string(),
    sourceDomain: z.string(),
    citationText: z.string(),
    reliabilityTier: z.number().int().min(1).max(4),
    licenseNote: z.string().nullable().optional(),
    parserVersion: z.string(),
});
export const snapshotSchema = z.object({
    id: z.string(),
    version: z.string(),
    status: snapshotStatusSchema,
    publishedAt: z.string().nullable(),
    scope: z.array(z.string()),
    notes: z.string().nullable().optional(),
});
export const companyDetailSchema = companySchema.extend({
    primaryRegion: z.string(),
    activeSnapshotId: z.string().nullable(),
    summary: z.string().nullable().optional(),
    lastUpdatedAt: z.string().nullable().optional(),
});
export const companyDetailResponseSchema = z.object({
    item: companyDetailSchema,
    source: backendSourceSchema,
});
export const companyOverviewSchema = z.object({
    companyId: z.string(),
    companyName: z.string(),
    activeSnapshotId: z.string().nullable(),
    totalRelations: z.number().int().min(0),
    tier1SupplierCount: z.number().int().min(0),
    supplierCount: z.number().int().min(0),
    highRiskRelationCount: z.number().int().min(0),
    evidenceCount: z.number().int().min(0),
    evidenceCoverage: z.number().min(0).max(1),
    lastUpdatedAt: z.string().nullable(),
    source: backendSourceSchema,
});
export const graphNodeSchema = z.object({
    id: z.string(),
    entityType: entityTypeSchema.exclude(["SupplyRelation", "Evidence", "Snapshot"]),
    label: z.string(),
    company: companyDetailSchema.optional(),
    country: z.string().optional(),
    marketCapUsd: z.number().nullable().optional(),
    importanceScore: z.number().min(0).max(1).optional(),
});
export const relationSchema = z.object({
    id: z.string(),
    sourceId: z.string(),
    targetId: z.string(),
    relationshipType: relationshipTypeSchema,
    relationshipSubtype: z.string().nullable().optional(),
    tier: z.number().int().min(1),
    depthFromMag7: z.number().int().min(0),
    confidence: confidenceSchema,
    confidenceScore: z.number().min(0).max(1),
    summary: z.string(),
    productScope: z.array(z.string()).default([]),
    notes: z.string().nullable().optional(),
    evidenceIds: z.array(z.string()).default([]),
    primaryEvidenceId: z.string().nullable().optional(),
    evidenceCount: z.number().int().min(0),
    snapshotId: z.string(),
    status: relationStatusSchema,
    sourceMethod: z.string().nullable().optional(),
    sourceCount: z.number().int().min(0).optional(),
    lineageKey: z.string().nullable().optional(),
    lastVerifiedAt: z.string().nullable().optional(),
    validFrom: z.string().nullable().optional(),
    validTo: z.string().nullable().optional(),
    evidence: z.array(evidenceSchema).optional(),
});
export const subgraphQuerySchema = z.object({
    companyId: z.string(),
    depth: z.coerce.number().int().min(1).max(5).default(2),
    relationshipTypes: z
        .union([relationshipTypeSchema, z.array(relationshipTypeSchema)])
        .transform((value) => Array.isArray(value) ? value : [value])
        .optional(),
    snapshot: z.string().default("published"),
    includeEvidence: z.coerce.boolean().default(false),
});
export const subgraphSchema = z.object({
    snapshot: snapshotSchema,
    nodes: z.array(graphNodeSchema),
    relations: z.array(relationSchema),
});
export const relationEvidenceResponseSchema = z.object({
    relationId: z.string(),
    items: z.array(evidenceSchema),
    total: z.number().int().min(0),
    source: backendSourceSchema,
});
export const standardizedImportRelationRecordSchema = z.object({
    relation_id: z.string(),
    snapshot_id: z.string(),
    company: z.string(),
    company_slug: z.string(),
    supplier: z.string(),
    supplier_slug: z.string(),
    tier: z.number().int().min(1),
    depth_from_mag7: z.number().int().min(0),
    relationship_type: relationshipTypeSchema,
    relationship_subtype: z.string(),
    product_scope: z.array(z.string()).min(1),
    evidence_ids: z.array(z.string()).min(1),
    primary_evidence_id: z.string(),
    evidence_date: z.string(),
    evidence_date_resolution: z.string(),
    evidence_excerpt: z.string(),
    source_url: z.string().url(),
    confidence_label: confidenceSchema,
    confidence_score: z.number().min(0).max(1),
    source_method: z.string(),
    source_count: z.number().int().min(1),
    status: relationStatusSchema,
    summary: z.string(),
    notes: z.string().optional(),
    lineage_key: z.string(),
    source_report_path: z.string(),
    last_verified_at: z.string(),
});
export const standardizedImportEvidenceRecordSchema = z.object({
    evidence_id: z.string(),
    relation_id: z.string(),
    source_type: sourceTypeSchema,
    title: z.string(),
    publisher: z.string(),
    source_url: z.string().url(),
    source_domain: z.string(),
    published_at: z.string(),
    published_at_resolution: z.string(),
    retrieved_at: z.string(),
    excerpt: z.string(),
    citation_text: z.string(),
    page_ref: z.string().optional(),
    language: z.string().optional(),
    reliability_tier: z.number().int().min(1).max(4),
    parser_version: z.string(),
    license_note: z.string().optional(),
    source_report_path: z.string(),
    notes: z.string().optional(),
});
export const standardizedImportPackageSchema = z.object({
    relations: z.array(standardizedImportRelationRecordSchema).min(1),
    evidence: z.array(standardizedImportEvidenceRecordSchema).min(1),
});
export const importRelationsRequestSchema = z.object({
    requestId: z.string(),
    source: z.string(),
    dataVersion: z.string(),
    schemaVersion: z.string().default("mag7-supply-chain.import-relations.v2"),
    relations: z.array(standardizedImportRelationRecordSchema).min(1),
});
export const importRelationsFieldCatalog = [
    {
        name: "relation_id",
        type: "string",
        required: true,
        description: "Stable relation primary key from the normalized package.",
    },
    {
        name: "snapshot_id",
        type: "string",
        required: true,
        description: "Snapshot identifier that versions this relation fact.",
    },
    {
        name: "company",
        type: "string",
        required: true,
        description: "Downstream company display label.",
    },
    {
        name: "company_slug",
        type: "string",
        required: true,
        description: "Canonical downstream company slug.",
    },
    {
        name: "supplier",
        type: "string",
        required: true,
        description: "Upstream supplier display label.",
    },
    {
        name: "supplier_slug",
        type: "string",
        required: true,
        description: "Canonical upstream supplier slug.",
    },
    {
        name: "tier",
        type: "integer",
        required: true,
        description: "Supplier tier relative to the downstream company.",
    },
    {
        name: "depth_from_mag7",
        type: "integer",
        required: true,
        description: "Traversal depth from the Mag7 anchor company.",
    },
    {
        name: "relationship_type",
        type: "enum",
        required: true,
        description: "Normalized supply-chain relationship type.",
    },
    {
        name: "relationship_subtype",
        type: "string",
        required: true,
        description: "Human-readable subtype preserved from research normalization.",
    },
    {
        name: "product_scope",
        type: "string[]",
        required: true,
        description: "Lossless array of products, materials, services, or technologies in scope.",
    },
    {
        name: "evidence_ids",
        type: "string[]",
        required: true,
        description: "All evidence identifiers attached to the relation.",
    },
    {
        name: "primary_evidence_id",
        type: "string",
        required: true,
        description: "Primary evidence identifier for summary and ranking.",
    },
    {
        name: "evidence_date",
        type: "string",
        required: true,
        description: "Canonical evidence date in ISO-8601 string form.",
    },
    {
        name: "evidence_date_resolution",
        type: "string",
        required: true,
        description: "How the evidence date was resolved during normalization.",
    },
    {
        name: "evidence_excerpt",
        type: "string",
        required: true,
        description: "Supporting excerpt kept for auditability and UI display.",
    },
    {
        name: "source_url",
        type: "string",
        required: true,
        description: "Canonical URL for the primary evidence source.",
    },
    {
        name: "confidence_label",
        type: "enum",
        required: true,
        description: "Display confidence bucket.",
    },
    {
        name: "confidence_score",
        type: "number",
        required: true,
        description: "Continuous confidence score between 0 and 1.",
    },
    {
        name: "source_method",
        type: "string",
        required: true,
        description: "Collection method used to derive the relation.",
    },
    {
        name: "source_count",
        type: "integer",
        required: true,
        description: "Number of supporting sources considered during normalization.",
    },
    {
        name: "status",
        type: "enum",
        required: true,
        description: "Lifecycle status of the relation fact.",
    },
    {
        name: "summary",
        type: "string",
        required: true,
        description: "Canonical analyst summary for the relation.",
    },
    {
        name: "notes",
        type: "string",
        required: false,
        description: "Optional analyst notes and caveats.",
    },
    {
        name: "lineage_key",
        type: "string",
        required: true,
        description: "Lineage key used for deduplication and version tracking.",
    },
    {
        name: "source_report_path",
        type: "string",
        required: true,
        description: "Collector output path where the evidence bundle originated.",
    },
    {
        name: "last_verified_at",
        type: "string",
        required: true,
        description: "Latest verification timestamp for this relation.",
    },
];
