import type {
  CompanyDetailDTO,
  EvidenceDTO,
  SnapshotDTO,
  SubgraphDTO,
} from "@mag7/contracts";

const snapshot: SnapshotDTO = {
  id: "snapshot:2026-06-14.1",
  version: "2026.06.14-01",
  status: "published",
  publishedAt: "2026-06-14T00:00:00.000Z",
  scope: ["company:AAPL", "company:MSFT", "company:NVDA"],
  notes: "Mock snapshot for backend bootstrap",
};

const companies: CompanyDetailDTO[] = [
  {
    id: "company:AAPL",
    ticker: "AAPL",
    name: "Apple",
    canonicalName: "Apple",
    displayName: "Apple",
    entityType: "Company",
    companyType: "public_company",
    country: "US",
    isMag7: true,
    marketCapUsd: 3100000000000,
    description: "Consumer hardware and services",
    aliases: ["Apple Inc."],
    entityProfile: {
      canonicalName: "Apple",
      displayName: "Apple",
      legalEntities: [
        {
          id: "alias:company:AAPL:apple-inc",
          name: "Apple Inc.",
          normalizedName: "appleinc",
          aliasType: "legal_entity",
          language: null,
          isPrimary: true,
          validFrom: null,
          validTo: null,
          validFromResolution: null,
          validToResolution: null,
          source: "mock_seed",
          notes: null,
        },
      ],
      brands: [],
      aliases: [
        {
          id: "alias:company:AAPL:apple",
          name: "Apple",
          normalizedName: "apple",
          aliasType: "canonical",
          language: null,
          isPrimary: true,
          validFrom: null,
          validTo: null,
          validFromResolution: null,
          validToResolution: null,
          source: "mock_seed",
          notes: null,
        },
      ],
    },
    active: true,
    importanceScore: 1,
    primaryRegion: "US",
    activeSnapshotId: snapshot.id,
    summary: "Consumer hardware and services company with concentrated foundry and assembly dependencies.",
    lastUpdatedAt: snapshot.publishedAt,
  },
  {
    id: "company:TSMC",
    ticker: "TSM",
    name: "TSMC",
    canonicalName: "TSMC",
    displayName: "TSMC",
    entityType: "Company",
    companyType: "manufacturer",
    country: "TW",
    isMag7: false,
    marketCapUsd: 910000000000,
    description: "Semiconductor foundry",
    aliases: ["Taiwan Semiconductor Manufacturing Company"],
    entityProfile: {
      canonicalName: "TSMC",
      displayName: "TSMC",
      legalEntities: [
        {
          id: "alias:company:TSMC:tsmc-legal",
          name: "Taiwan Semiconductor Manufacturing Company Limited",
          normalizedName: "taiwansemiconductormanufacturingcompanylimited",
          aliasType: "legal_entity",
          language: null,
          isPrimary: true,
          validFrom: null,
          validTo: null,
          validFromResolution: null,
          validToResolution: null,
          source: "mock_seed",
          notes: null,
        },
      ],
      brands: [],
      aliases: [
        {
          id: "alias:company:TSMC:tsmc",
          name: "TSMC",
          normalizedName: "tsmc",
          aliasType: "canonical",
          language: null,
          isPrimary: true,
          validFrom: null,
          validTo: null,
          validFromResolution: null,
          validToResolution: null,
          source: "mock_seed",
          notes: null,
        },
      ],
    },
    active: true,
    importanceScore: 0.82,
    primaryRegion: "TW",
    activeSnapshotId: snapshot.id,
    summary: "Advanced semiconductor foundry serving leading AI and consumer hardware programs.",
    lastUpdatedAt: snapshot.publishedAt,
  },
  {
    id: "company:ASML",
    ticker: "ASML",
    name: "ASML",
    canonicalName: "ASML",
    displayName: "ASML",
    entityType: "Company",
    companyType: "supplier",
    country: "NL",
    isMag7: false,
    marketCapUsd: 410000000000,
    description: "Lithography equipment supplier",
    aliases: [],
    entityProfile: {
      canonicalName: "ASML",
      displayName: "ASML",
      legalEntities: [],
      brands: [],
      aliases: [
        {
          id: "alias:company:ASML:asml",
          name: "ASML",
          normalizedName: "asml",
          aliasType: "canonical",
          language: null,
          isPrimary: true,
          validFrom: null,
          validTo: null,
          validFromResolution: null,
          validToResolution: null,
          source: "mock_seed",
          notes: null,
        },
      ],
    },
    active: true,
    importanceScore: 0.74,
    primaryRegion: "NL",
    activeSnapshotId: snapshot.id,
    summary: "Critical semiconductor equipment provider for advanced-node manufacturing.",
    lastUpdatedAt: snapshot.publishedAt,
  },
];

const evidence: EvidenceDTO[] = [
  {
    id: "evidence:apple-supplier-list-2024",
    sourceType: "supplier_report",
    title: "Apple Supplier List 2024",
    publisher: "Apple",
    url: "https://s203.q4cdn.com/367071867/files/doc_downloads/2024/04/Apple-Supplier-List.pdf",
    publishedAt: "2024-04-18T00:00:00.000Z",
    publishedAtResolution: "published_at",
    coverageStart: "2024",
    coverageEnd: "2024",
    coverageStartResolution: "year",
    coverageEndResolution: "year",
    retrievedAt: "2026-06-14T00:00:00.000Z",
    excerpt: "Apple discloses key manufacturing and component suppliers in its annual supplier list.",
    pageRef: "Supplier List",
    language: "en",
    hash: "sha256:apple-supplier-list-2024",
    sourceDomain: "apple.com",
    citationText: "Apple discloses key manufacturing and component suppliers in its annual supplier list.",
    reliabilityTier: 1,
    licenseNote: null,
    parserVersion: "mock-1.0.0",
  },
  {
    id: "evidence:asml-annual-2025",
    sourceType: "supplier_report",
    title: "ASML Annual Report 2025",
    publisher: "ASML",
    url: "https://www.asml.com/en/investors/annual-report",
    publishedAt: "2026-02-12T00:00:00.000Z",
    publishedAtResolution: "published_at",
    coverageStart: null,
    coverageEnd: null,
    coverageStartResolution: null,
    coverageEndResolution: null,
    retrievedAt: "2026-06-14T00:00:00.000Z",
    excerpt: "EUV demand continues to be driven by advanced logic foundry customers.",
    pageRef: "Annual report",
    language: "en",
    hash: "sha256:asml-annual-2025",
    sourceDomain: "asml.com",
    citationText: "EUV demand continues to be driven by advanced logic foundry customers.",
    reliabilityTier: 2,
    licenseNote: null,
    parserVersion: "mock-1.0.0",
  },
];

export const mockSubgraph: SubgraphDTO = {
  snapshot,
  nodes: companies.map((company) => ({
    id: company.id,
    entityType: "Company",
    label: company.name,
    company,
    country: company.country,
    marketCapUsd: company.marketCapUsd,
    importanceScore: company.importanceScore,
  })),
  relations: [
    {
      id: "rel:tsmc-aapl-manufacturing",
      sourceId: "company:TSMC",
      targetId: "company:AAPL",
      relationshipType: "manufacturing",
      tier: 1,
      depthFromMag7: 1,
      confidence: "strong_evidence",
      confidenceScore: 0.88,
      summary: "TSMC 为 Apple 提供先进制程晶圆代工能力。",
      relationshipSubtype: "wafer_foundry",
      productScope: ["advanced silicon manufacturing"],
      notes: "Mock relation aligned to standardized import field set.",
      evidenceIds: [evidence[0].id],
      primaryEvidenceId: evidence[0].id,
      evidenceCount: 1,
      snapshotId: snapshot.id,
      status: "approved",
      sourceMethod: "mock_seed",
      evidenceDate: "2024",
      evidenceDateResolution: "year",
      evidenceDateNormalized: "2024-01-01",
      evidenceDateIsNormalized: true,
      sourceCount: 1,
      lineageKey: "lineage:tsmc:aapl:manufacturing",
      lastVerifiedAt: "2026-06-14T00:00:00.000Z",
      validFrom: "2024",
      validFromResolution: "year",
      validTo: null,
      validToResolution: null,
      validityNote: "Mock seeded from annual supplier reporting coverage.",
      evidence: [evidence[0]],
    },
    {
      id: "rel:asml-tsmc-equipment",
      sourceId: "company:ASML",
      targetId: "company:TSMC",
      relationshipType: "equipment_supply",
      tier: 2,
      depthFromMag7: 2,
      confidence: "strong_evidence",
      confidenceScore: 0.84,
      summary: "ASML 为 TSMC 提供 EUV 光刻设备。",
      relationshipSubtype: "lithography_equipment",
      productScope: ["EUV lithography equipment"],
      notes: "Mock relation aligned to standardized import field set.",
      evidenceIds: [evidence[1].id],
      primaryEvidenceId: evidence[1].id,
      evidenceCount: 1,
      snapshotId: snapshot.id,
      status: "approved",
      sourceMethod: "mock_seed",
      evidenceDate: "2026-02-12",
      evidenceDateResolution: "day",
      evidenceDateNormalized: null,
      evidenceDateIsNormalized: false,
      sourceCount: 1,
      lineageKey: "lineage:asml:tsmc:equipment",
      lastVerifiedAt: "2026-06-14T00:00:00.000Z",
      validFrom: null,
      validFromResolution: null,
      validTo: null,
      validToResolution: null,
      validityNote: null,
      evidence: [evidence[1]],
    },
  ],
};

export const mockCompanies = companies;
