import type {
  CompanyDTO,
  EvidenceDTO,
  SnapshotDTO,
  SubgraphDTO,
} from "../../../packages/contracts/src/index.js";

const snapshot: SnapshotDTO = {
  id: "snapshot:2026-06-14.1",
  version: "2026.06.14-01",
  status: "published",
  publishedAt: "2026-06-14T00:00:00.000Z",
  scope: ["company:AAPL", "company:MSFT", "company:NVDA"],
  notes: "Mock snapshot for backend bootstrap",
};

const companies: CompanyDTO[] = [
  {
    id: "company:AAPL",
    ticker: "AAPL",
    name: "Apple",
    entityType: "Company",
    companyType: "public_company",
    country: "US",
    isMag7: true,
    marketCapUsd: 3100000000000,
    description: "Consumer hardware and services",
    aliases: ["Apple Inc."],
    active: true,
    importanceScore: 1,
  },
  {
    id: "company:TSMC",
    ticker: "TSM",
    name: "TSMC",
    entityType: "Company",
    companyType: "manufacturer",
    country: "TW",
    isMag7: false,
    marketCapUsd: 910000000000,
    description: "Semiconductor foundry",
    aliases: ["Taiwan Semiconductor Manufacturing Company"],
    active: true,
    importanceScore: 0.82,
  },
  {
    id: "company:ASML",
    ticker: "ASML",
    name: "ASML",
    entityType: "Company",
    companyType: "supplier",
    country: "NL",
    isMag7: false,
    marketCapUsd: 410000000000,
    description: "Lithography equipment supplier",
    aliases: [],
    active: true,
    importanceScore: 0.74,
  },
];

const evidence: EvidenceDTO[] = [
  {
    id: "evidence:apple-supplier-list-2024",
    sourceType: "supplier_report",
    title: "Apple Supplier List 2024",
    publisher: "Apple",
    url: "https://s203.q4cdn.com/367071867/files/doc_downloads/2024/04/Apple-Supplier-List.pdf",
    publishedAt: "2024-04-18T00:00:00.000Z",
    retrievedAt: "2026-06-14T00:00:00.000Z",
    excerpt: "Apple discloses key manufacturing and component suppliers in its annual supplier list.",
    pageRef: "Supplier List",
    language: "en",
    hash: "sha256:apple-supplier-list-2024",
  },
  {
    id: "evidence:asml-annual-2025",
    sourceType: "supplier_report",
    title: "ASML Annual Report 2025",
    publisher: "ASML",
    url: "https://www.asml.com/en/investors/annual-report",
    publishedAt: "2026-02-12T00:00:00.000Z",
    retrievedAt: "2026-06-14T00:00:00.000Z",
    excerpt: "EUV demand continues to be driven by advanced logic foundry customers.",
    pageRef: "Annual report",
    language: "en",
    hash: "sha256:asml-annual-2025",
  },
];

export const mockSubgraph: SubgraphDTO = {
  snapshot,
  nodes: companies.map((company) => ({
    id: company.id,
    entityType: "Company",
    label: company.name,
    company,
    country: company.country,
    marketCapUsd: company.marketCapUsd,
    importanceScore: company.importanceScore,
  })),
  relations: [
    {
      id: "rel:tsmc-aapl-manufacturing",
      sourceId: "company:TSMC",
      targetId: "company:AAPL",
      relationshipType: "manufacturing",
      tier: 1,
      depthFromMag7: 1,
      confidence: "strong_evidence",
      confidenceScore: 0.88,
      summary: "TSMC 为 Apple 提供先进制程晶圆代工能力。",
      evidenceCount: 1,
      snapshotId: snapshot.id,
      status: "approved",
      validFrom: "2024-01-01",
      validTo: null,
      evidence: [evidence[0]],
    },
    {
      id: "rel:asml-tsmc-equipment",
      sourceId: "company:ASML",
      targetId: "company:TSMC",
      relationshipType: "equipment_supply",
      tier: 2,
      depthFromMag7: 2,
      confidence: "strong_evidence",
      confidenceScore: 0.84,
      summary: "ASML 为 TSMC 提供 EUV 光刻设备。",
      evidenceCount: 1,
      snapshotId: snapshot.id,
      status: "approved",
      validFrom: "2024-01-01",
      validTo: null,
      evidence: [evidence[1]],
    },
  ],
};

export const mockCompanies = companies;
